tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "antigen"
brew "fzf"
brew "git"
brew "mas"
brew "tig"
brew "yarn"
brew "z"
brew "zsh"
cask "alfred"
cask "calibre"
cask "dash"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "pritunl"
cask "sequel-pro"
cask "visual-studio-code"
mas "Magnet", id: 441258766
mas "Pixelmator Pro", id: 1289583905
mas "Slack", id: 803453959
